services:
  platform:
    container_name: platform
    build:
      context: .
      target: prod
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - .:/app/src/
    env_file:
      - ./.env
    environment:
      REWORKD_PLATFORM_HOST: 0.0.0.0
      REWORKD_PLATFORM_DB_HOST: agentgpt_db
      REWORKD_PLATFORM_DB_PORT: "3307"
      REWORKD_PLATFORM_DB_USER: "reworkd_platform"
      REWORKD_PLATFORM_DB_PASS: "reworkd_platform"
      REWORKD_PLATFORM_DB_BASE: "reworkd_platform"
    depends_on:
      - agentgpt_db
    networks:
      - agentgpt_network

  agentgpt_db:
    image: mysql:8.0
    container_name: agentgpt_db
    restart: always
    build:
      context: ./db
    ports:
      - "3308:3307"
    environment:
      MYSQL_DATABASE: "reworkd_platform"
      MYSQL_USER: "reworkd_platform"
      MYSQL_PASSWORD: "reworkd_platform"
      MYSQL_ROOT_PASSWORD: "reworkd_platform"
      MYSQL_TCP_PORT: 3307
    volumes:
      - agentgpt_db:/var/lib/mysql
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    networks:
      - agentgpt_network

volumes:
  agentgpt_db:

networks:
  agentgpt_network:
    external: true
